import Head from "next/head";
import { useState } from "react";
import Board from "@/components/Board";
import BoardTest from "@/components/BoardTest";
import Layout from "@/components/Layout";
import KanbanBoard from "@/components/KanbanBoard";

export default function Home() {
  return (
    <>
      <Head>
        <title>TaskLab | Project Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          {/* <BoardTest /> */}
          {/* <Board /> */}
          <KanbanBoard />
        </Layout>
      </main>
    </>
  );
}
