import Head from "next/head";
import { useState } from "react";
import Layout from "@/layouts/Layout";
import KanbanBoard from "@/components/KanbanBoard";

export default function Home() {
  return (
    <>
      <Head>
        <title>TaskLab | Project Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>{/* <NewBoard /> */}</Layout>
      </main>
    </>
  );
}
